// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygdbtqlwaaxjtwwhkcow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlnZGJ0cWx3YWF4anR3d2hrY293Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0MDkwNjYsImV4cCI6MjA4NDk4NTA2Nn0.Hx_fMsb8tCqO3Dg7mTJCGTQAlIsR7wreVl9-UNhpRUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});